### ISSUE TITLE
Getting IndexError on conversion

### ISSUE THREAD

**Issue by pisymbol** [ardamavi/Intel-Movidius-NCS-Keras#1]
```
$ python -c 'import keras; print(keras.__version__)'
Using TensorFlow backend.
2.1.3
$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.4.0
$ python3 keras2graph.py model.json inception_v3_input dense_25/Softmax incept3_ft_weights.h5 ./graph
Using TensorFlow backend.
2018-01-28 17:43:23.298471: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-28 17:43:23.407829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
totalMemory: 11.90GiB freeMemory: 11.61GiB
2018-01-28 17:43:23.407862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:0a:00.0, compute capability: 6.1)
Model Summary:
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
inception_v3 (Model)         (None, 8, 8, 2048)        21802784
_________________________________________________________________
global_average_pooling2d_1 ( (None, 2048)              0
_________________________________________________________________
dense_24 (Dense)             (None, 1024)              2098176
_________________________________________________________________
dense_25 (Dense)             (None, 200)               205000
=================================================================
Total params: 24,105,960
Trainable params: 21,768,352
Non-trainable params: 2,337,608
_________________________________________________________________
None
mvNCCompile v02.00, Copyright @ Movidius Ltd 2016

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py:766: DeprecationWarning: builtin type EagerTensor has no __module__ attribute
  EagerTensor = c_api.TFE_Py_InitEagerTensor(_EagerTensorBase)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
Traceback (most recent call last):
  File "/usr/local/bin/mvNCCompile", line 118, in <module>
    create_graph(args.network, args.inputnode, args.outputnode, args.outfile, args.nshaves, args.inputsize, args.weights)
  File "/usr/local/bin/mvNCCompile", line 104, in create_graph
    net = parse_tensor(args, myriad_config)
  File "/usr/local/bin/ncsdk/Controllers/TensorFlowParser.py", line 290, in parse_tensor
    if have_first_input(strip_tensor_id(node.outputs[0].name)):
IndexError: list index out of range
```

The model.json file was created via keras.models.load_model() and then model.to_json() etc.

What am I doing wrong?

**Comment by ardamavi** [comment]
There is a problem in converting TensorFlow graph (converted from Keras, this is OK) to NCS graph format. The problem is not your source. The project is still in construction. Stay tuned!

**Comment by ardamavi** [comment]
This project is open source for this error. We are looking help for this.

**Comment by pisymbol** [comment]
Is there any word around for this? I really need to get this to work.

**Comment by pisymbol** [comment]
Btw, I was able to get past that issue by adding a small patch but then I see:

[Error 5] Toolkit Error: Stage Details Not Supported: FusedBatchNorm inputs mean and variance are not defined.  The graph is not created for inference.

**Comment by ardamavi** [comment]
If you share your patch, let's try to fix it together.

**Comment by pisymbol** [comment]
Well, I need to look at it more. But solving the IndexError was simple as:

```
-- TensorFlowParser.py	2018-01-29 11:37:22.912714875 +0000
+++ TensorFlowParser.py.patch	2018-01-29 11:36:51.172559957 +0000
@@ -287,7 +287,7 @@
                 for a in node.outputs:
                     print("           OUT:", a.name)
             if not inputfound:
-                if have_first_input(strip_tensor_id(node.outputs[0].name)):
+                if node.outputs and have_first_input(strip_tensor_id(node.outputs[0].name)):
                     inputfound = True
                     if debug:
                         print('Starting to process')
```
