### ISSUE TITLE
InvalidArgumentError 

### ISSUE THREAD

**Issue by Hans-Einar** [ardamavi/Intel-Movidius-NCS-Keras#2]

**Comment by ardamavi** [comment]
The project is still in construction. Stay tuned!
This project is open source. If you share your patch, let's try to fix it together.

**Comment by SandorSeres** [comment]
Hi,
I have similar issue:
My model is
Using TensorFlow backend.
Model Summary:
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv_I (Conv2D)              (None, 60, 200, 32)       608       
_________________________________________________________________
conv_Ia (Conv2D)             (None, 60, 200, 32)       9248      
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 30, 100, 32)       0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 30, 100, 32)       0         
_________________________________________________________________
conv_II (Conv2D)             (None, 30, 100, 64)       18496     
_________________________________________________________________
conv_IIa (Conv2D)            (None, 30, 100, 64)       36928     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 15, 50, 64)        0         
_________________________________________________________________
dropout_6 (Dropout)          (None, 15, 50, 64)        0         
_________________________________________________________________
conv_III (Conv2D)            (None, 15, 50, 128)       73856     
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 7, 25, 128)        0         
_________________________________________________________________
conv_IIIa (Conv2D)           (None, 7, 25, 128)        147584    
_________________________________________________________________
flatten_2 (Flatten)          (None, 22400)             0         
_________________________________________________________________
dense_4 (Dense)              (None, 512)               11469312  
_________________________________________________________________
dropout_7 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_8 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 4)                 2052      
=================================================================
Total params: 12,020,740
Trainable params: 12,020,740
Non-trainable params: 0
__________________________
When I want to compile for the stick, I am getting Invalid argument
Command is:
$ mvNCCompile ./TF_Model/tf_model.meta -in conv_I_input -on dense_6/Softmax -o ./graph
-------The error -----------------------------
Caused by op 'dropout_5/keras_learning_phase', defined at:
  File "/usr/local/bin/mvNCCompile", line 118, in <module>
    create_graph(args.network, args.inputnode, args.outputnode, args.outfile, args.nshaves, args.inputsize, args.weights)
  File "/usr/local/bin/mvNCCompile", line 104, in create_graph
    net = parse_tensor(args, myriad_config)
  File "/usr/local/bin/ncsdk/Controllers/TensorFlowParser.py", line 213, in parse_tensor
    saver = tf.train.import_meta_graph(path, clear_devices=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1810, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/meta_graph.py", line 660, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'dropout_5/keras_learning_phase' with dtype bool
	 [[Node: dropout_5/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
------------------------------------
So it is may not because of the dropout layer?
S&|

**Comment by oraoto** [comment]
I have come across similar problem, solved by modifying ncsdk source. 

In `/usr/local/bin/ncsdk/Controllers/TensorFlowParser.py` line 1059, add a feed_dict to eval:

```
# desired_shape = node.inputs[1].eval() 
desired_shape = node.inputs[1].eval(feed_dict={inputnode + ':0' : input_data})
```

And get grid of dropout layer, you should `K.set_learning_phase(0)` before loading the model.

**Comment by DongChen06** [comment]
@oraoto 
When I modified the TensorFlowParser.py, I got another problem:
```
/home/dongdong/anaconda3/envs/tf-nogpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py:766: DeprecationWarning: builtin type EagerTensor has no __module__ attribute
  EagerTensor = c_api.TFE_Py_InitEagerTensor(_EagerTensorBase)
/home/dongdong/anaconda3/envs/tf-nogpu/lib/python3.5/site-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
/home/dongdong/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/dongdong/anaconda3/envs/tf-nogpu/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py:509: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)
[Error 5] Toolkit Error: Stage Details Not Supported: PlaceholderWithDefault
```

**Comment by oraoto** [comment]
@Derekabc here's my [modified TensorFlowParser.py](https://gist.github.com/oraoto/7656c7593b5bc7e481118e8c167d4d13),  and [some working examples](https://github.com/oraoto/learn_ml/tree/master/ncs).

**Comment by DongChen06** [comment]
Hi,
    can you send me your picture(th.jpeg) for VGG-16?  I want to do a experiment on your code.  Thank you very much.


------------------
Best,
Chen Dong


 




------------------ Original ------------------

**Comment by oraoto** [comment]
@Derekabc th.jpg is random zebra image from [Bing image search](https://bing.com/images/search?q=zebra):smile:, you can try different images from the [ImageNet](http://image-net.org/) project.

**Comment by DongChen06** [comment]
Thank you for your patience!  I runned your code and get the same results like  yours.  I will study your code closely. 


------------------
Best,
Chen Dong


 




------------------ Original ------------------

**Comment by DongChen06** [comment]
HI,
       How do you know the name of input and output nodes when you use ncsdk to compile your model?   I cannot find the definition in your codes.
       Thank you very much!


------------------
Best,
Chen Dong


 




------------------ Original ------------------

**Comment by oraoto** [comment]
@Derekabc I use `tensorboard --logdir logs`to view the graph and get the names.

**Comment by Derekabc** [comment]
Hi,
      Many thanks to your patience!!
      My name is Dong Chen(陈东)，and I am now a first-year PhD student of Michigan State University. I see your address is China, are you a chinese?


------------------
Best,
Chen Dong


 




------------------ Original ------------------

**Comment by RoberttsengTAO** [comment]
@Derekabc  
[Error 5] Toolkit Error: Stage Details Not Supported: PlaceholderWithDefault
Hi, I have the same error, How did you fix?

**Comment by umer-rasheed** [comment]
Hi 
I am getting this error

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py:509: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-c8297959cd91> in <module>()
      1 # Converting Keras model to Intel Movidius technology internal compiled format graph:
----> 2 keras2graph.keras_to_graph('Keras_Model/model.json', 'input_1', 'activation_7/Softmax', 'Keras_Model/weights.h5', './graph', False)

~/Downloads/Intel-Movidius-NCS-Keras-master/keras2graph.py in keras_to_graph(model_path, model_in, model_out, weights_path, graph_path, take_tf_files)
     36 def keras_to_graph(model_path, model_in, model_out, weights_path, graph_path, take_tf_files = False):
     37     # Getting Keras Model:
---> 38     keras_model = get_keras_model(model_path, weights_path)
     39 
     40     # Saving TensorFlow Model from Keras Model:

~/Downloads/Intel-Movidius-NCS-Keras-master/keras2graph.py in get_keras_model(model_path, weights_path)
     13 
     14     # Readed model file to model:
---> 15     model = model_from_json(model)
     16 
     17     # Loading weights:

/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py in model_from_json(json_string, custom_objects)
    366     config = json.loads(json_string)
    367     from ..layers import deserialize
--> 368     return deserialize(config, custom_objects=custom_objects)
    369 
    370 

/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    143                     config['config'],
    144                     custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 145                                         list(custom_objects.items())))
    146             with CustomObjectScope(custom_objects):
    147                 return cls.from_config(config['config'])

/usr/local/lib/python3.5/dist-packages/keras/engine/network.py in from_config(cls, config, custom_objects)
   1025                 if layer in unprocessed_nodes:
   1026                     for node_data in unprocessed_nodes.pop(layer):
-> 1027                         process_node(layer, node_data)
   1028 
   1029         name = config.get('name')

/usr/local/lib/python3.5/dist-packages/keras/engine/network.py in process_node(layer, node_data)
    984             # and building the layer if needed.
    985             if input_tensors:
--> 986                 layer(unpack_singleton(input_tensors), **kwargs)
    987 
    988         def process_layer(layer_data):

/usr/local/lib/python3.5/dist-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    455             # Actually call the layer,
    456             # collecting output(s), mask(s), and shape(s).
--> 457             output = self.call(inputs, **kwargs)
    458             output_mask = self.compute_mask(inputs, previous_mask)
    459 

/usr/local/lib/python3.5/dist-packages/keras/layers/core.py in call(self, inputs)
    293 
    294     def call(self, inputs):
--> 295         return self.activation(inputs)
    296 
    297     def get_config(self):

/usr/local/lib/python3.5/dist-packages/keras/activations.py in softmax(x, axis)
     27     ndim = K.ndim(x)
     28     if ndim == 2:
---> 29         return K.softmax(x)
     30     elif ndim > 2:
     31         e = K.exp(x - K.max(x, axis=axis, keepdims=True))

/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py in softmax(x, axis)
   3152         A tensor.
   3153     """
-> 3154     return tf.nn.softmax(x, axis=axis)
   3155 
   3156 

TypeError: softmax() got an unexpected keyword argument 'axis'

Kind;ly let me know how to fix this issue. Thanks.

**Comment by martinbel** [comment]
@ardamavi I've managed to convert a keras model to a working NCS graph for object detection. There is an example in my [repo](https://github.com/martinbel/yolo2NCS) . Perhaps you can get some ideas from this for your project. 
The issues I had converting the keras model was mostly with the Batch Norm layers. This simply didn't  compile. To make it work I had to redefine the graph in tensorflow, assign the weights and freeze that new graph. A fairly tedious but functional process. Perhaps there is a better way...
